version: "3.9"
services:
  api:
    image: api
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - redis

  worker:
    image: worker
    container_name: worker
    depends_on:
      - redis

  redis:
    image: redis
    container_name: journalink-redis
    ports:
      - "6379:6379"