version: "3.9"
services:
  api:
    image: tabish1511/journalink:api
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    image: tabish1511/journalink:worker
    container_name: worker
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis
    container_name: journalink-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
