name: Build and Deploy Docker-Compose Services

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push API Image
      uses: docker/build-push-action@v2
      with:
        context: ./api
        file: ./api/Dockerfile
        push: true
        tags: tabish1511/journalink:api

    - name: Build and Push Worker Image
      uses: docker/build-push-action@v2
      with:
        context: ./worker
        file: ./worker/Dockerfile
        push: true
        tags: tabish1511/journalink:worker