name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'worker/**'
      - 'docker-compose-server.yaml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push API Image
      uses: docker/build-push-action@v2
      with:
        context: ./api
        file: ./api/Dockerfile
        push: true
        tags: tabish1511/journalink:api

    - name: Build and Push Worker Image
      uses: docker/build-push-action@v2
      with:
        context: ./worker
        file: ./worker/Dockerfile
        push: true
        tags: tabish1511/journalink:worker

    - name: Upload docker-compose File to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: ./docker-compose-server.yaml
        target: /home/ubuntu/journalink-be/

    - name: Export DATABASE_URL to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" | sudo tee -a /etc/environment
          source /etc/environment

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Pull the latest images
          sudo docker pull tabish1511/journalink:api
          sudo docker pull tabish1511/journalink:worker
          sudo docker pull redis:latest
          
          # Stop and remove existing containers if they exist
          sudo docker-compose -f /home/ubuntu/journalink-be/docker-compose-server.yaml down
          
          # Run docker-compose with updated images
          sudo docker-compose -f /home/ubuntu/journalink-be/docker-compose-server.yaml up -d

